package com.china.acetech.ToolPackage.data.repo.greenDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CUSTOM_COURSE.
 */
public class CustomCourse {

    private Long id;
    private String courseID;
    private String courseName;
    private Integer categoryID;
    private Integer trainSegmentID;
    private java.util.Date syncTime;
    private Long CountOfSum;
    private Long CountInWeek;
    private Integer Level;
    private Boolean isFavorite;
    private String firstPicturePath;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CustomCourse() {
    }

    public CustomCourse(Long id) {
        this.id = id;
    }

    public CustomCourse(Long id, String courseID, String courseName, Integer categoryID, Integer trainSegmentID, java.util.Date syncTime, Long CountOfSum, Long CountInWeek, Integer Level, Boolean isFavorite, String firstPicturePath) {
        this.id = id;
        this.courseID = courseID;
        this.courseName = courseName;
        this.categoryID = categoryID;
        this.trainSegmentID = trainSegmentID;
        this.syncTime = syncTime;
        this.CountOfSum = CountOfSum;
        this.CountInWeek = CountInWeek;
        this.Level = Level;
        this.isFavorite = isFavorite;
        this.firstPicturePath = firstPicturePath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCourseID() {
        return courseID;
    }

    public void setCourseID(String courseID) {
        this.courseID = courseID;
    }

    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public Integer getCategoryID() {
        return categoryID;
    }

    public void setCategoryID(Integer categoryID) {
        this.categoryID = categoryID;
    }

    public Integer getTrainSegmentID() {
        return trainSegmentID;
    }

    public void setTrainSegmentID(Integer trainSegmentID) {
        this.trainSegmentID = trainSegmentID;
    }

    public java.util.Date getSyncTime() {
        return syncTime;
    }

    public void setSyncTime(java.util.Date syncTime) {
        this.syncTime = syncTime;
    }

    public Long getCountOfSum() {
        return CountOfSum;
    }

    public void setCountOfSum(Long CountOfSum) {
        this.CountOfSum = CountOfSum;
    }

    public Long getCountInWeek() {
        return CountInWeek;
    }

    public void setCountInWeek(Long CountInWeek) {
        this.CountInWeek = CountInWeek;
    }

    public Integer getLevel() {
        return Level;
    }

    public void setLevel(Integer Level) {
        this.Level = Level;
    }

    public Boolean getIsFavorite() {
        return isFavorite;
    }

    public void setIsFavorite(Boolean isFavorite) {
        this.isFavorite = isFavorite;
    }

    public String getFirstPicturePath() {
        return firstPicturePath;
    }

    public void setFirstPicturePath(String firstPicturePath) {
        this.firstPicturePath = firstPicturePath;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
