package com.china.acetech.ToolPackage.data.repo.greenDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.china.acetech.ToolPackage.data.repo.greenDao.SportInfo;

import com.china.acetech.ToolPackage.data.repo.greenDao.SportInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sportInfoDaoConfig;

    private final SportInfoDao sportInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sportInfoDaoConfig = daoConfigMap.get(SportInfoDao.class).clone();
        sportInfoDaoConfig.initIdentityScope(type);

        sportInfoDao = new SportInfoDao(sportInfoDaoConfig, this);

        registerDao(SportInfo.class, sportInfoDao);
    }
    
    public void clear() {
        sportInfoDaoConfig.getIdentityScope().clear();
    }

    public SportInfoDao getSportInfoDao() {
        return sportInfoDao;
    }

}
