package com.china.acetech.ToolPackage.data.repo.greenDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SPORT_INFO.
 */
public class SportInfo {

    private Long id;
    private java.util.Date calendar;
    private Integer number;
    private Integer timestyle;
    private Integer steps;
    private Integer distance;
    private Integer calories;
    private Long active;
    private Integer floor;
    private Integer sleepstatus;
    private java.util.Date lastsynctime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SportInfo() {
    }

    public SportInfo(Long id) {
        this.id = id;
    }

    public SportInfo(Long id, java.util.Date calendar, Integer number, Integer timestyle, Integer steps, Integer distance, Integer calories, Long active, Integer floor, Integer sleepstatus, java.util.Date lastsynctime) {
        this.id = id;
        this.calendar = calendar;
        this.number = number;
        this.timestyle = timestyle;
        this.steps = steps;
        this.distance = distance;
        this.calories = calories;
        this.active = active;
        this.floor = floor;
        this.sleepstatus = sleepstatus;
        this.lastsynctime = lastsynctime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getCalendar() {
        return calendar;
    }

    public void setCalendar(java.util.Date calendar) {
        this.calendar = calendar;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Integer getTimestyle() {
        return timestyle;
    }

    public void setTimestyle(Integer timestyle) {
        this.timestyle = timestyle;
    }

    public Integer getSteps() {
        return steps;
    }

    public void setSteps(Integer steps) {
        this.steps = steps;
    }

    public Integer getDistance() {
        return distance;
    }

    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    public Integer getCalories() {
        return calories;
    }

    public void setCalories(Integer calories) {
        this.calories = calories;
    }

    public Long getActive() {
        return active;
    }

    public void setActive(Long active) {
        this.active = active;
    }

    public Integer getFloor() {
        return floor;
    }

    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    public Integer getSleepstatus() {
        return sleepstatus;
    }

    public void setSleepstatus(Integer sleepstatus) {
        this.sleepstatus = sleepstatus;
    }

    public java.util.Date getLastsynctime() {
        return lastsynctime;
    }

    public void setLastsynctime(java.util.Date lastsynctime) {
        this.lastsynctime = lastsynctime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
