package com.china.acetech.ToolPackage.data.domain;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table BRACELET_INFO.
 */
public class BraceletInfo_AP extends Entity{

	private long id;
    private String bracelet;
    private String version;
    private String MD5;
    private String MacAddress;
    private String fileName;

    public static final int INFO_ID = 4516;
    public static final int USER_INFO_ID = 2457;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BraceletInfo_AP() {
    }

    public BraceletInfo_AP(String bracelet) {
        this.bracelet = bracelet;
    }

    public BraceletInfo_AP(Long id, String bracelet, String version, String MD5, String MacAddress, String fileName) {
        setEntityID(id);
        this.bracelet = bracelet;
        this.version = version;
        this.MD5 = MD5;
        this.MacAddress = MacAddress;
        this.fileName = fileName;
    }

    public static BraceletInfo_AP getEmptyEntity(){
    	BraceletInfo_AP entity = new BraceletInfo_AP();
    	entity.setID(INFO_ID);
    	entity.setBracelet("");
    	entity.setVersion("");
    	entity.setMD5("");
    	entity.setMacAddress("");
    	entity.setFileName("");
    	
    	return entity;
    }
    
    
	@Override
	public String getEntityName() {
		return "BraceletInfo";
	}
	
	public void setID(long s_id){
		id = s_id;
	}
	public long getID(){
		return id;
	}
	
    public String getBracelet() {
        return bracelet;
    }

    public void setBracelet(String bracelet) {
        this.bracelet = bracelet;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getMD5() {
        return MD5;
    }

    public void setMD5(String md5) {
        this.MD5 = md5;
    }
    
    public String getMacAddress() {
        return MacAddress;
    }

    public void setMacAddress(String macAddress) {
        this.MacAddress = macAddress;
    }
    
    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
