package com.china.acetech.ToolPackage.data.domain;

import java.util.Date;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CUSTOM_COURSE.
 */
public class CustomCourse_AP  extends Entity{

	private Long id;
    private String courseID;
    private String courseName;
    private Integer categoryID;
    private Integer trainSegmentID;
    private Date syncTime;
    private Long CountOfSum;
    private Long CountInWeek;
    private Integer Level;
    private Boolean isFavorite;
    private String firstPicturePath;

    // KEEP FIELDS - put your custom fields here
    private List<CustomCourseRelative_AP> relativeList;

    public void setActionList(List<CustomCourseRelative_AP> list){
    	relativeList = list;
    }
    public List<CustomCourseRelative_AP> getActionList(){
    	return relativeList;
    }
    // KEEP FIELDS END

	public static class ConstValue{
		public static final int BODYPART_UpperLimb = 1;
		public static final int BODYPART_LowerLimb = 2;
		public static final int BODYPART_Trunk = 4;
		public static final int BODYPART_UpperLimb_LowerLimb = BODYPART_UpperLimb | BODYPART_LowerLimb;
		public static final int BODYPART_UpperLimb_Trunk = BODYPART_UpperLimb | BODYPART_Trunk;
		public static final int BODYPART_Trunk_LowerLimb = BODYPART_Trunk | BODYPART_LowerLimb;
		public static final int BODYPART_UpperLimb_LowerLimb_Trunk = BODYPART_UpperLimb | BODYPART_LowerLimb | BODYPART_Trunk;
		
		
		public static final int CATEGORY_MUSCLE = 1;
		public static final int CATEGORY_SOFT = 2;
		
		public static final int LEVEL_EASY = 0;
		public static final int LEVEL_NORMAL = 1;
		public static final int LEVEL_HARD = 2;
	}
	
    public CustomCourse_AP() {
    }

    public CustomCourse_AP(Long id) {
    	this.id = id;
    }

	@Override
	public String getEntityName() {
		return "CustomCourse";
	}
	
    public CustomCourse_AP(Long id, String courseID, String courseName, Integer categoryID, Integer trainSegmentID, Date syncTime, Long CountOfSum, Long CountInWeek, Integer Level, Boolean isFavorite, String firstPicturePath) {
        this.id = id;
        this.courseID = courseID;
        this.courseName = courseName;
        this.categoryID = categoryID;
        this.trainSegmentID = trainSegmentID;
        this.syncTime = syncTime;
        this.CountOfSum = CountOfSum;
        this.CountInWeek = CountInWeek;
        this.Level = Level;
        this.isFavorite = isFavorite;
        this.firstPicturePath = firstPicturePath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public String getCourseID() {
        return courseID;
    }

    public void setCourseID(String courseID) {
        this.courseID = courseID;
    }

    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public Integer getCategoryID() {
        return categoryID;
    }

    public void setCategoryID(Integer categoryID) {
        this.categoryID = categoryID;
    }

    public Integer getTrainSegmentID() {
        return trainSegmentID;
    }

    public void setSyncTime(Date actionSyncTime) {
        this.syncTime = actionSyncTime;
    }

    public Date getSyncTime() {
        return syncTime;
    }
    
    public void setTrainSegmentID(Integer trainSegmentID) {
        this.trainSegmentID = trainSegmentID;
    }

    public Long getCountOfSum() {
        return CountOfSum;
    }

    public void setCountOfSum(Long CountOfSum) {
        this.CountOfSum = CountOfSum;
    }

    public Long getCountInWeek() {
        return CountInWeek;
    }

    public void setCountInWeek(Long CountInWeek) {
        this.CountInWeek = CountInWeek;
    }

    public Integer getLevel() {
        return Level;
    }

    public void setLevel(Integer Level) {
        this.Level = Level;
    }

    public Boolean getIsFavorite() {
        return isFavorite;
    }

    public void setIsFavorite(Boolean isFavorite) {
        this.isFavorite = isFavorite;
    }

    public String getFirstPicturePath() {
        return firstPicturePath;
    }

    public void setFirstPicturePath(String firstPicturePath) {
        this.firstPicturePath = firstPicturePath;
    }
    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
